
	CREATE SCHEMA GESTOR_STOCK;
	
	GO

	CREATE TABLE GESTOR_STOCK.TipoProduto (
		numTipo SMALLINT NOT NULL PRIMARY KEY,
		designacao VARCHAR(255) NOT NULL
	);

	GO

	CREATE TABLE GESTOR_STOCK.CondicaoPagamento (
		numCondicao SMALLINT NOT NULL PRIMARY KEY,
		designacao VARCHAR(255) NOT NULL
	);

	GO

	CREATE TABLE GESTOR_STOCK.Fornecedor (
		nif BIGINT NOT NULL PRIMARY KEY,
		nome VARCHAR(255) NOT NULL,
		endereco VARCHAR(255) NOT NULL,
		numFax BIGINT NOT NULL UNIQUE,
		condPagamento SMALLINT NOT NULL FOREIGN KEY REFERENCES GESTOR_STOCK.CondicaoPagamento(numCondicao),
		tipoProd SMALLINT NOT NULL FOREIGN KEY REFERENCES GESTOR_STOCK.TipoProduto(numTipo)
	);

	GO

	CREATE TABLE GESTOR_STOCK.Produto (
		codigo BIGINT NOT NULL PRIMARY KEY,
		nome VARCHAR(255) NOT NULL,
		preco DECIMAL(9,2) NOT NULL,
		taxaIVA DECIMAL(2,2) NOT NULL,
		categoria SMALLINT NOT NULL FOREIGN KEY REFERENCES GESTOR_STOCK.TipoProduto(numTipo)
	);

	GO

	CREATE TABLE GESTOR_STOCK.Encomenda (
		numEnc BIGINT NOT NULL PRIMARY KEY,
		dataEncomenda DATETIME NOT NULL,
		fornecedor BIGINT NOT NULL FOREIGN KEY REFERENCES GESTOR_STOCK.Fornecedor(nif)
	);

	GO 

	CREATE TABLE GESTOR_STOCK.ProdutosEncomenda (
		codigoProd BIGINT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES GESTOR_STOCK.Produto(codigo),
		quantidade SMALLINT NOT NULL,
		encomendaAssociada BIGINT NOT NULL FOREIGN KEY REFERENCES GESTOR_STOCK.Encomenda(numEnc)
	);

	GO