	CREATE SCHEMA GESTOR_CONFERENCIAS;

	GO

	CREATE TABLE GESTOR_CONFERENCIAS.Conferencia (
		codConferencia BIGINT NOT NULL PRIMARY KEY,
		dataInicio DATETIME NOT NULL,
		dataFim DATETIME NOT NULL
	);

	GO

	CREATE TABLE GESTOR_CONFERENCIAS.ArtigoCientifico (
		numRegisto BIGINT NOT NULL PRIMARY KEY,
		titulo VARCHAR(255) NOT NULL,
		conferencia BIGINT NOT NULL FOREIGN KEY REFERENCES GESTOR_CONFERENCIAS.Conferencia(codConferencia)
	);

	GO

	CREATE TABLE GESTOR_CONFERENCIAS.Instituicao (
		nome VARCHAR(255) NOT NULL PRIMARY KEY,
		endereco VARCHAR(255) NOT NULL
	);

	GO

	CREATE TABLE GESTOR_CONFERENCIAS.Autor (
		email VARCHAR(255) NOT NULL PRIMARY KEY,
		nome VARCHAR(255) NOT NULL,
		instituicao VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES GESTOR_CONFERENCIAS.Instituicao(nome)
	);

	GO

	CREATE TABLE GESTOR_CONFERENCIAS.AutoresArtigo (
		autor VARCHAR(255) NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES GESTOR_CONFERENCIAS.Autor(email),
		artigo BIGINT NOT NULL FOREIGN KEY REFERENCES GESTOR_CONFERENCIAS.ArtigoCientifico(numRegisto)
	);

	GO

	CREATE TABLE GESTOR_CONFERENCIAS.Participante (
		email VARCHAR(255) NOT NULL PRIMARY KEY,
		nome VARCHAR(255) NOT NULL,
		morada VARCHAR(255) NOT NULL,
		dataInscricao DATETIME NOT NULL,
		conferencia BIGINT NOT NULL FOREIGN KEY REFERENCES GESTOR_CONFERENCIAS.Conferencia(codConferencia)
	);

	GO

	CREATE TABLE GESTOR_CONFERENCIAS.Estudante (
		email VARCHAR(255) NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES GESTOR_CONFERENCIAS.Participante(email),
		nomeInstituicao VARCHAR(255) NOT NULL FOREIGN KEY REFERENCES GESTOR_CONFERENCIAS.Instituicao(nome),
		certificado VARCHAR(255) NOT NULL
	);

	GO

	CREATE TABLE GESTOR_CONFERENCIAS.NaoEstudante (
		email VARCHAR(255) NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES GESTOR_CONFERENCIAS.Participante(email),
		referencia BIGINT NOT NULL
	);

	GO







