	CREATE SCHEMA PRESCRICAO_MEDICAMENTOS;

	GO

	CREATE TABLE PRESCRICAO_MEDICAMENTOS.Paciente (
		numUtente BIGINT NOT NULL PRIMARY KEY,
		nome VARCHAR(255) NOT NULL,
		endereco VARCHAR(255) NOT NULL,
		dataNasc DATETIME NOT NULL
	);

	GO

	CREATE TABLE PRESCRICAO_MEDICAMENTOS.Medico (
		numSNS BIGINT NOT NULL PRIMARY KEY,
		nome VARCHAR(255) NOT NULL,
		especialidade VARCHAR(255) NOT NULL
	);

	GO

	CREATE TABLE PRESCRICAO_MEDICAMENTOS.Farmacia (
		nif BIGINT NOT NULL PRIMARY KEY,
		nome VARCHAR(255) NOT NULL,
		endereco VARCHAR(255) NOT NULL,
		telefone BIGINT NOT NULL UNIQUE
	);

	GO

	CREATE TABLE PRESCRICAO_MEDICAMENTOS.Farmaceutica (
		numReg BIGINT NOT NULL PRIMARY KEY,
		nome VARCHAR(255) NOT NULL,
		endereco VARCHAR(255) NOT NULL,
		telefone BIGINT NOT NULL UNIQUE
	);

	GO

	CREATE TABLE PRESCRICAO_MEDICAMENTOS.Farmaco (
		numID BIGINT NOT NULL PRIMARY KEY,
		nome VARCHAR(255) NOT NULL,
		formula VARCHAR(1000) NOT NULL,
		farmaceutica BIGINT NOT NULL FOREIGN KEY REFERENCES PRESCRICAO_MEDICAMENTOS.Farmaceutica(numReg)
	);

	GO

	CREATE TABLE PRESCRICAO_MEDICAMENTOS.Prescricao (
		numPresc BIGINT NOT NULL PRIMARY KEY,
		dataCriacaoPresc DATETIME NOT NULL,
		dataProcessamentoPresc DATETIME NOT NULL,
		numPaciente BIGINT NOT NULL FOREIGN KEY REFERENCES PRESCRICAO_MEDICAMENTOS.Paciente(numUtente),
		numMedico BIGINT NOT NULL FOREIGN KEY REFERENCES PRESCRICAO_MEDICAMENTOS.Medico(numSNS),
		numFarmacia BIGINT NOT NULL FOREIGN KEY REFERENCES PRESCRICAO_MEDICAMENTOS.Farmacia(nif)

	);

	GO

	CREATE TABLE PRESCRICAO_MEDICAMENTOS.ListaFarmacos (
		numFarmaco BIGINT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES PRESCRICAO_MEDICAMENTOS.Farmaco(numID),
		quantidade SMALLINT NOT NULL,
		numPrescricao BIGINT NOT NULL FOREIGN KEY REFERENCES PRESCRICAO_MEDICAMENTOS.Prescricao(numPresc)
	);

	GO
